"""add_data_status_to_stocks

Revision ID: e93774f9e58e
Revises: f5c476d3311c
Create Date: 2026-06-24 23:48:57.596203

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e93774f9e58e'
down_revision: Union[str, None] = 'f5c476d3311c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('stocks', sa.Column('data_status', sa.Text(), nullable=True))
    op.add_column('stocks', sa.Column('data_error', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('stocks', 'data_error')
    op.drop_column('stocks', 'data_status')
    # ### end Alembic commands ###
