"""initial_schema

Revision ID: f5c476d3311c
Revises: 
Create Date: 2026-06-24 20:13:16.962842

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f5c476d3311c'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('alerts',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('security_id', sa.Text(), nullable=False),
    sa.Column('signal_date', sa.Text(), nullable=False),
    sa.Column('alert_price', sa.Float(), nullable=False),
    sa.Column('valid_days', sa.Integer(), nullable=False),
    sa.Column('expires_at', sa.Text(), nullable=False),
    sa.Column('status', sa.Text(), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.Column('triggered_at', sa.Text(), nullable=True),
    sa.Column('triggered_price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_alerts_status', 'alerts', ['status'], unique=False)
    op.create_index('idx_alerts_symbol', 'alerts', ['symbol'], unique=False)
    op.create_table('app_config',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('scan_time', sa.Text(), nullable=False),
    sa.Column('scan_percentage', sa.Float(), nullable=False),
    sa.Column('scan_days', sa.Integer(), nullable=False),
    sa.Column('alert_check_interval_mins', sa.Integer(), nullable=False),
    sa.Column('alert_check_start', sa.Text(), nullable=False),
    sa.Column('alert_check_end', sa.Text(), nullable=False),
    sa.Column('dhan_client_id', sa.Text(), nullable=False),
    sa.Column('dhan_access_token', sa.Text(), nullable=False),
    sa.Column('token_expires_at', sa.Text(), nullable=True),
    sa.Column('token_status', sa.Text(), nullable=False),
    sa.Column('telegram_bot_token', sa.Text(), nullable=False),
    sa.Column('telegram_chat_id', sa.Text(), nullable=False),
    sa.Column('updated_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candle_cache',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('security_id', sa.Text(), nullable=False),
    sa.Column('trade_date', sa.Text(), nullable=False),
    sa.Column('open', sa.Float(), nullable=False),
    sa.Column('high', sa.Float(), nullable=False),
    sa.Column('low', sa.Float(), nullable=False),
    sa.Column('close', sa.Float(), nullable=False),
    sa.Column('volume', sa.Integer(), nullable=False),
    sa.Column('fetched_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id', 'trade_date')
    )
    op.create_table('scan_signals',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('scan_date', sa.Text(), nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('security_id', sa.Text(), nullable=False),
    sa.Column('close_price', sa.Float(), nullable=False),
    sa.Column('start_price', sa.Float(), nullable=False),
    sa.Column('return_pct', sa.Float(), nullable=False),
    sa.Column('scan_days', sa.Integer(), nullable=False),
    sa.Column('scan_threshold', sa.Float(), nullable=False),
    sa.Column('created_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('scan_date', 'security_id')
    )
    op.create_index('idx_signals_date', 'scan_signals', ['scan_date'], unique=False)
    op.create_index('idx_signals_symbol', 'scan_signals', ['symbol'], unique=False)
    op.create_table('stocks',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('symbol', sa.Text(), nullable=False),
    sa.Column('name', sa.Text(), nullable=False),
    sa.Column('security_id', sa.Text(), nullable=False),
    sa.Column('exchange_segment', sa.Text(), nullable=False),
    sa.Column('universe_tag', sa.Text(), nullable=False),
    sa.Column('is_active', sa.Integer(), nullable=False),
    sa.Column('added_at', sa.Text(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('security_id')
    )
    op.create_table('alert_history',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('alert_id', sa.Integer(), nullable=False),
    sa.Column('event_type', sa.Text(), nullable=False),
    sa.Column('price', sa.Float(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('timestamp', sa.Text(), nullable=False),
    sa.ForeignKeyConstraint(['alert_id'], ['alerts.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_alert_id', 'alert_history', ['alert_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_history_alert_id', table_name='alert_history')
    op.drop_table('alert_history')
    op.drop_table('stocks')
    op.drop_index('idx_signals_symbol', table_name='scan_signals')
    op.drop_index('idx_signals_date', table_name='scan_signals')
    op.drop_table('scan_signals')
    op.drop_table('candle_cache')
    op.drop_table('app_config')
    op.drop_index('idx_alerts_symbol', table_name='alerts')
    op.drop_index('idx_alerts_status', table_name='alerts')
    op.drop_table('alerts')
    # ### end Alembic commands ###
